<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Flow.Audio</AssemblyName>
    <RootNamespace>Flow.Audio</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../flow-music-model/flow-music-model.csproj" />
  </ItemGroup>
</Project>
