import {createDemo,clone,uid,clamp,COLORS,SOURCE,sourceOf,visibleNotes,splitClip,duplicateClip,detachClip,History,validateProject,makeLayer} from './model.js';
import {PreviewAudio} from './audio.js';
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={play:'m7 4 13 8-13 8Z',pause:'M8 5v14M16 5v14',stop:'M6 6h12v12H6Z',rewind:'M5 4v16M19 5 7 12l12 7Z',loop:'M4 8h13l-3-3m6 11H7l3 3M4 8v5m16 3v-5',undo:'M9 5 3 10l6 5M3 10h11a6 6 0 0 1 0 12',redo:'m15 5 6 5-6 5m6-5H10a6 6 0 0 0 0 12',save:'M5 3h13l3 3v15H3V3Zm2 0v6h10V3M7 21v-8h10v8',download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',plus:'M12 4v16M4 12h16',code:'m8 5-6 7 6 7m8-14 6 7-6 7m-3-16-2 18',search:'M16 16 22 22M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',close:'m5 5 14 14M19 5 5 19'};
const icon=name=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.code}"/></svg>`;
const btn=(action,label,extra='')=>`<button data-action="${action}" ${extra}>${label}</button>`;
let doc=createDemo(),history=new History(),selected=doc.clips.at(-1).id,layerId=sourceOf(doc,doc.clips.at(-1)).layers[1].id;
let tab='piano',layout='beside',category='INST',search='',noteId=null,position=8,zoom=1,snap=.25,editorOpen=false,sourceShown=true;
let status='Demo project · generate to replace the seeded note preview',error=false,dirty=false,build=null,toastTimer,autosaveTimer;
const audio=new PreviewAudio();
try{const saved=localStorage.getItem('flow-workspace-v1');if(saved){doc=validateProject(JSON.parse(saved));selected=doc.clips.at(-1)?.id;layerId=null;status='Recovered your locally saved workspace';}}catch{status='Saved workspace could not be restored. Demo opened safely.';}
const selectedClip=()=>doc.clips.find(c=>c.id===selected),selectedSource=()=>{const c=selectedClip();return c&&sourceOf(doc,c);};
const selectedLayer=()=>{const s=selectedSource();return s?.layers.find(l=>l.id===layerId)||s?.layers[0];};
const selectedTrack=()=>doc.tracks.find(t=>t.id===selectedClip()?.trackId)||doc.tracks[0];
const pitchName=p=>['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'][p%12]+(Math.floor(p/12)-1);
function notify(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3200);}
function persist(){clearTimeout(autosaveTimer);autosaveTimer=setTimeout(()=>{try{localStorage.setItem('flow-workspace-v1',JSON.stringify(doc));}catch{notify('Local storage is full. Save a project file to keep your changes.');}},250);}
function refreshAudio(){if(audio.playing){position=audio.position();void audio.play(doc,position).catch(e=>notify(e.message));}}
function edit(label,change){const before=clone(doc);change();if(history.commit(label,before,doc)){dirty=true;persist();refreshAudio();}render();}
function saveSourceDraft(){const input=$('#source-code'),source=selectedSource();if(input&&source&&source.code!==input.value){const before=clone(doc);source.code=input.value;history.commit('Edit Flow source',before,doc);dirty=true;persist();}}
function selectClip(id){saveSourceDraft();selected=id;noteId=null;layerId=selectedSource()?.layers[0]?.id;render();}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function miniNotes(c,s){const notes=visibleNotes(s,c).slice(0,180),lo=Math.min(36,...notes.map(n=>n.pitch)),hi=Math.max(84,...notes.map(n=>n.pitch));return `<svg viewBox="0 0 400 36" preserveAspectRatio="none">${notes.map(n=>`<rect x="${n.start/c.length*400}" y="${3+(hi-n.pitch)/(hi-lo)*27}" width="${Math.max(2,n.duration/c.length*400-1)}" height="2.5" fill="${n.color}" opacity=".85"/>`).join('')}</svg>`;}
const totalBeats=()=>Math.max(64,...doc.clips.map(c=>Math.ceil((c.start+c.length)/16)*16));
function arrangement(){const total=totalBeats();return `<section class="arrangement panel"><div class="panel-head"><span class="eyebrow">Arrangement</span><span class="pill">${total/4} BARS</span><div class="flex"></div>${btn('split','Split','title="Split selected clip at playhead (S)"')}${btn('duplicate','Duplicate','title="Duplicate clip (Ctrl+D)"')}${btn('zoom-out','−','aria-label="Zoom out"')}${btn('zoom-in','+','aria-label="Zoom in"')}${btn('add-track','+ TRACK')}</div>
<div class="arr-scroll"><div class="timeline" style="width:${Math.max(100,zoom*100)}%"><div class="ruler-row"><div class="track-header">${doc.tracks.length} TRACKS / BEATS</div><div class="ruler" data-ruler>${Array.from({length:total/4},(_,i)=>`<span style="left:${i*4/total*100}%">${i+1}</span>`).join('')}${doc.loop.enabled?`<div class="loop-range" style="left:${doc.loop.start/total*100}%;width:${(doc.loop.end-doc.loop.start)/total*100}%"></div>`:''}<div class="playhead" data-arr-head></div></div></div>
${doc.tracks.map(t=>`<div class="track-row" style="--track:${t.color}"><div class="track-header"><div class="track-name">${esc(t.name)}</div><div class="track-controls">${btn('mute','M',`data-track="${t.id}" class="${t.mute?'active':''}" aria-label="Mute ${esc(t.name)}" aria-pressed="${t.mute}"`)}${btn('solo','S',`data-track="${t.id}" class="${t.solo?'active':''}" aria-label="Solo ${esc(t.name)}" aria-pressed="${t.solo}"`)}<small>${doc.clips.filter(c=>c.trackId===t.id).length} clips</small></div></div><div class="lane" data-track-lane="${t.id}">
${doc.clips.filter(c=>c.trackId===t.id).map(c=>{const s=sourceOf(doc,c);return `<div role="button" tabindex="0" aria-label="Clip ${esc(c.name)}" data-clip="${c.id}" class="clip ${c.id===selected?'selected':''} ${s.kind==='generated'?'generated':''}" style="--clip:${t.color};left:${c.start/total*100}%;width:${c.length/total*100}%"><div class="clip-title"><b>${esc(c.name)}</b>${s.kind==='generated'?'<span class="badge">FLOW</span>':''}</div>${miniNotes(c,s)}<div class="clip-handle" title="Trim clip end"></div></div>`;}).join('')}<div class="playhead" data-arr-head></div></div></div>`).join('')}
${!doc.clips.length?`<div class="empty"><h2>A new place to start.</h2><p>Write a phrase. Draw a note. Build something that sounds like you.</p>${btn('add-flow','+ FLOW CLIP','class="primary"')}${btn('add-notes','+ NOTE CLIP')}</div>`:''}</div></div></section>`;}
const library={INST:[['Sine','Pure, rounded tone','sine'],['Triangle','Soft bass & plucks','triangle'],['Sawtooth','Bright lead & texture','sawtooth'],['Square','Hollow, woody tone','square'],['Noise','Percussive texture','noise']],FX:[['Low-pass filter','Cutoff per note layer','filter'],['Stereo delay','One-tap echo','delay']],GEN:[['Layered motif','Bass + lead + pad','motif'],['Empty Flow source','Your next musical idea','blank']],FILE:[['Open project','Load .flowproject / JSON','open'],['New project','Start with a blank canvas','new']]};
function browser(){return `<aside class="browser panel"><div class="panel-head"><span class="eyebrow">Library</span><div class="flex"></div><span class="small-info">LOCAL</span></div><input class="search" id="search" placeholder="Search sounds…" aria-label="Search library" value="${esc(search)}"><div class="segments">${Object.keys(library).map(c=>btn('category',c,`data-category="${c}" class="${c===category?'active':''}"`)).join('')}</div><div class="browser-list">${library[category].filter(x=>x.join(' ').toLowerCase().includes(search.toLowerCase())).map(([name,description,key])=>`<button class="library-item ${selectedLayer()?.instrument===key?'active':''}" data-action="library" data-key="${key}"><span class="library-glyph">${category==='GEN'?'⤳':category==='FX'?'≋':'∿'}</span><span>${esc(name)}<small>${esc(description)}</small></span></button>`).join('')}</div><div class="browser-foot"><div class="eyebrow">Code is an instrument.</div><p>Generate notes, keep their source.<br>Arrange the result like any clip.</p><br>${btn('add-flow','+ GENERATE WITH FLOW','class="primary"')}</div></aside>`;}
function piano(){const c=selectedClip(),s=selectedSource(),layer=selectedLayer();if(!c||!s)return `<div class="empty"><h2>No clip selected</h2><p>Select a clip in the arrangement, or add a new note clip.</p>${btn('add-notes','+ NOTE CLIP')}</div>`;
    const notes=visibleNotes(s,c),pitches=notes.map(n=>n.pitch),lo=Math.max(0,Math.min(60,...pitches)-2),hi=Math.min(127,Math.max(83,...pitches)+2),rows=hi-lo+1;
    return `<div class="piano-tools"><select id="layer-picker" aria-label="Note layer">${s.layers.map(l=>`<option value="${l.id}" ${l.id===layer?.id?'selected':''}>${esc(l.name)}</option>`).join('')}</select><span class="badge" style="--clip:${layer?.color}">${s.kind==='generated'?'GENERATED':'EDITABLE'}</span><div class="flex"></div>${btn('transpose-down','−1','aria-label="Transpose selected note down"')}${btn('transpose-up','+1','aria-label="Transpose selected note up"')}${btn('delete-note','×','aria-label="Delete selected note"')}<select id="snap" aria-label="Note snap">${[[1,'¼'],[.5,'⅛'],[.25,'¹⁄₁₆']].map(([v,l])=>`<option value="${v}" ${snap===v?'selected':''}>${l}</option>`).join('')}</select></div>
<div class="roll-scroll"><div class="roll" style="height:${rows*16}px"><div>${Array.from({length:rows},(_,i)=>{const p=hi-i;return `<div class="key-row ${[1,3,6,8,10].includes(p%12)?'black':''}"><div class="key-label" data-key-pitch="${p}">${p%12===0?pitchName(p):''}</div></div>`;}).join('')}</div><div class="note-field" data-hi="${hi}" data-lo="${lo}">${notes.map(n=>`<div class="note ${n.id===noteId?'selected':''}" role="button" tabindex="0" aria-label="${pitchName(n.pitch)} note" data-note="${n.id}" data-layer="${n.layerId}" title="${pitchName(n.pitch)} · velocity ${Math.round(n.velocity*127)}" style="left:${n.start/c.length*100}%;width:${Math.max(.15,n.duration/c.length*100-.1)}%;top:${(hi-n.pitch)*16+1}px;height:14px;background:linear-gradient(${n.color},color-mix(in srgb,${n.color} 65%,#172331));opacity:${n.layerId===layer?.id?1:.4}"><span class="note-edge"></span></div>`).join('')}<div class="playhead" data-roll-head></div></div></div></div><div class="roll-foot"><span>${notes.length} NOTES · ${s.layers.length} LAYERS</span><div class="flex"></div><span>${s.kind==='generated'?'Convert to edit notes':'Double-click to draw · drag to move'}</span></div>`;}
function range(label,property,value,min,max,step,target='layer'){return `<div class="form-row"><label>${label}<span>${Number(value).toFixed(property==='cutoff'?0:2)}</span></label><input type="range" aria-label="${label}" data-range="${property}" data-target="${target}" min="${min}" max="${max}" step="${step}" value="${value}"></div>`;}
function devices(){const l=selectedLayer();if(!l)return '<div class="empty">Select a clip to shape its sound.</div>';return `<div class="devices"><div class="device"><span class="eyebrow">01 / INSTRUMENT</span><h3>${esc(l.name)}</h3><select id="instrument" aria-label="Layer instrument">${library.INST.map(([n,,v])=>`<option value="${v}" ${l.instrument===v?'selected':''}>${n}</option>`).join('')}</select>${range('Layer gain','gain',l.gain,0,1,.01)}${range('Layer pan','pan',l.pan,-1,1,.01)}</div><div class="device"><span class="eyebrow">02 / EFFECTS</span><h3>Filter + delay</h3>${range('Filter cutoff · Hz','cutoff',l.cutoff,40,20000,10)}${range('Delay mix','delay',l.delay,0,.8,.01)}<span class="small-info">Browser preview chain<br>Flow plugin graphs come later.</span></div></div>`;}
function mixer(){return `<div class="mixer">${doc.tracks.map(t=>`<div class="strip" style="--track:${t.color}"><b>${esc(t.name)}</b><small>GAIN</small><input type="range" min="0" max="1" step=".01" value="${t.gain}" data-range="gain" data-target="track" data-track="${t.id}" aria-label="${esc(t.name)} gain"><small>${(t.gain*100).toFixed(0)}%</small><div>${btn('mute','M',`data-track="${t.id}" class="${t.mute?'active':''}" aria-label="Mute ${esc(t.name)}"`)} ${btn('solo','S',`data-track="${t.id}" class="${t.solo?'active':''}" aria-label="Solo ${esc(t.name)}"`)}</div></div>`).join('')}</div>`;}
function sourcePane(){const s=selectedSource(),generated=s?.kind==='generated';return `<section class="source-pane panel ${editorOpen?'source-overlay':''}" ${sourceShown?'':'hidden'}><div class="panel-head"><span class="source-file">${icon('code')} ${esc(s?.name||'No source selected')}${generated?' · .flow':''}</span><div class="flex"></div><span class="source-state">${build?'BUILDING':s?.code!==s?.builtCode?'EDITED':generated?'SOURCE':'NOTES'}</span>${btn('expand-source',editorOpen?'↙':'↗','aria-label="Expand source editor"')}</div><div class="editor-wrap"><div class="line-numbers" aria-hidden="true">${Array.from({length:(s?.code||'').split('\n').length+1},(_,i)=>i+1).join('\n')}</div><textarea id="source-code" class="source-editor" spellcheck="false" aria-label="Flow composition source" ${generated?'':'readonly'} placeholder="Select a Flow clip to edit its source.">${esc(s?.code||'// This clip contains editable notes.\n// Add a Flow clip to generate music with code.')}</textarea></div><div class="source-footer">${btn('generate',`${icon('play')} GENERATE`,`${!generated||build?'disabled':''} class="primary"`)}${build?btn('cancel-build','Cancel'):''}<div class="flex"></div><span class="keyhint">CTRL + ENTER</span></div><div id="diagnostic" role="status" class="diagnostic ${error?'error':''}">${esc(status)}</div></section>`;}
function inspector(){const c=selectedClip(),s=selectedSource(),l=selectedLayer(),n=l?.notes.find(n=>n.id===noteId);return `<aside class="inspector panel"><div class="panel-head"><span class="eyebrow">Inspector</span><div class="flex"></div><span class="small-info">${s?.kind==='generated'?'FLOW CLIP':'SELECTION'}</span></div><div class="inspector-content">${c?`<div class="eyebrow" style="color:${selectedTrack()?.color}">● ${esc(selectedTrack()?.name)}</div><div class="selection-name">${esc(c.name)}</div><div class="property"><span>START</span><span>bar ${(c.start/4+1).toFixed(2)}</span></div><div class="property"><span>LENGTH</span><span>${c.length.toFixed(2)} beats</span></div><div class="property"><span>SOURCE OFFSET</span><span>${c.offset.toFixed(2)} beats</span></div><div class="property"><span>LINKED CLIPS</span><span>${doc.clips.filter(x=>x.sourceId===s.id).length}</span></div><div class="rule"></div><div class="source-link">${s.kind==='generated'?'⤳ GENERATED FROM FLOW':'♫ EDITABLE NOTE CONTENT'}<br><span class="small-info">${s.layers.length} note layers · revision ${s.revision}</span></div><p>Moving and splitting keeps the source intact. Regenerate updates linked clips.</p>${btn('convert',s.kind==='generated'?'CONVERT TO EDITABLE NOTES':'MAKE INDEPENDENT',`title="Create independent note content for this clip"`)}<div class="rule"></div><div class="eyebrow">${esc(l?.name||'')} / SOUND</div>${l?`<div class="form-row"><select id="inspector-instrument" aria-label="Preview instrument">${library.INST.map(([name,,v])=>`<option value="${v}" ${v===l.instrument?'selected':''}>${name}</option>`).join('')}</select></div>${range('Layer gain','gain',l.gain,0,1,.01)}${range('Filter cutoff · Hz','cutoff',l.cutoff,40,20000,10)}${n?range('Note velocity','velocity',n.velocity,.01,1,.01,'note'):''}`:''}`:'<div class="empty">Select a clip to inspect its source and sound.</div>'}<div class="rule"></div><div class="eyebrow">Project context</div><div class="property"><span>TEMPO</span><span>${doc.bpm} BPM</span></div><div class="property"><span>METER / TUNING</span><span>4/4 · 12-TET</span></div><div class="rule"></div><div class="eyebrow">History</div>${history.past.slice(-5).map(a=>`<div class="history">↳ ${esc(a.label)}</div>`).join('')||'<p>No edits yet</p>'}</div></aside>`;}
function render(){const scroll=$('.arr-scroll')?.scrollLeft||0,rollScroll=$('.roll-scroll')?.scrollTop;
    $('#app').innerHTML=`<header class="top"><div class="brand">flow<small>WORKSPACE</small></div><div class="separator"></div><div class="project-title"><span class="eyebrow">PROJECT ${dirty?'●':''}</span><input class="name-input" id="project-name" aria-label="Project name" maxlength="120" value="${esc(doc.name)}"></div><div class="transport">${btn('rewind',icon('rewind'),'class="icon" aria-label="Rewind"')}${btn('play',icon(audio.playing?'pause':'play'),`id="play-button" class="icon ${audio.playing?'active playing':''}" aria-label="${audio.playing?'Pause':'Play'}"`)}${btn('stop',icon('stop'),'class="icon" aria-label="Stop"')}</div><div class="clock" id="clock">003 · 1 · 000</div><label class="tempo-label"><input class="tempo" id="bpm" type="number" min="30" max="300" value="${doc.bpm}" aria-label="Tempo BPM"></label><span class="eyebrow signature">BPM<br>4 / 4</span>${btn('loop',icon('loop'),`class="icon ${doc.loop.enabled?'active':''}" aria-label="Toggle loop" aria-pressed="${doc.loop.enabled}"`)}<div class="flex"></div>${btn('undo',icon('undo'),`class="icon" aria-label="Undo" ${history.past.length?'':'disabled'}`)}${btn('redo',icon('redo'),`class="icon" aria-label="Redo" ${history.future.length?'':'disabled'}`)}${btn('open','OPEN','id="open"')}${btn('save',`${icon('save')} SAVE`,'aria-label="Save project"')}${btn('export',`${icon('download')} EXPORT`,'class="primary" aria-label="Export WAV"')}<div class="separator"></div><div class="top-meta">BROWSER PREVIEW<br><span class="green">●</span> Web Audio · stereo</div></header>
<nav class="layout-bar" aria-label="Workspace layout"><span class="eyebrow">WORKSPACE</span>${[['classic','Classic'],['stacked','Stacked sides'],['beside','Source beside']].map(([id,name])=>btn('layout',name,`data-layout="${id}" class="${layout===id?'active':''}"`)).join('')}<div class="flex"></div><span class="prototype-label">DESIGN PROTOTYPE / 01</span>${btn('toggle-source','{ } SOURCE',`aria-pressed="${sourceShown}"`)}${btn('help','?','aria-label="Keyboard shortcuts"')}</nav>
<main class="workspace layout-${layout} ${sourceShown?'':'source-hidden'} ${editorOpen?'editor-open':''}">${browser()}${arrangement()}<div class="splitter" role="separator" aria-label="Resize lower panels" aria-orientation="horizontal" tabindex="0"></div><div class="detail"><section class="music-pane panel"><div class="panel-head"><div class="tabs" role="tablist">${[['piano','PIANO ROLL'],['devices','DEVICES'],['mixer','MIXER']].map(([id,name])=>btn('tab',name,`data-tab="${id}" role="tab" aria-selected="${tab===id}" class="${tab===id?'active':''}"`)).join('')}</div><div class="flex"></div><span class="small-info">${esc(selectedClip()?.name||'')}</span></div>${tab==='piano'?piano():`<div class="panel-body">${tab==='devices'?devices():mixer()}</div>`}</section><div class="source-split" role="separator" tabindex="0" aria-label="Resize source panel" aria-orientation="vertical"></div>${sourcePane()}</div>${inspector()}</main>
<footer class="bottom-status"><span><i class="status-led"></i><span id="play-state">STOPPED</span></span><span class="optional">${doc.clips.length} CLIPS · ${doc.sources.reduce((a,s)=>a+s.layers.reduce((n,l)=>n+l.notes.length,0),0)} SOURCE NOTES</span><div class="flex"></div><span class="optional">SPACE play · S split · CTRL+D duplicate</span><span>AUDIO UNDERRUNS: UNKNOWN</span></footer>`;
    if($('.arr-scroll'))$('.arr-scroll').scrollLeft=scroll;if($('.roll-scroll'))$('.roll-scroll').scrollTop=rollScroll??Math.max(0,($('.roll')?.offsetHeight||0)/2-100);applyPaneSizes();updatePlayhead();
}
let bottomSize=null,sourceSize=null;
function applyPaneSizes(){if(bottomSize&&innerWidth>650)$('.workspace').style.gridTemplateRows=`minmax(160px,1fr) 7px ${bottomSize}px`;if(sourceSize&&$('.source-pane'))$('.source-pane').style.flex=`0 0 ${sourceSize}%`;}
function updatePlayhead(){const p=audio.playing?audio.position():position;$('#clock').textContent=`${String(Math.floor(p/4)+1).padStart(3,'0')} · ${Math.floor(p%4)+1} · ${String(Math.floor(p%1*960)).padStart(3,'0')}`;$('#play-state').textContent=audio.playing?'PLAYING':'STOPPED';for(const el of document.querySelectorAll('[data-arr-head]'))el.style.left=`${p/totalBeats()*100}%`;const c=selectedClip(),el=$('[data-roll-head]');if(el&&c){el.style.left=`${(p-c.start)/c.length*100}%`;el.style.display=p>=c.start&&p<c.start+c.length?'block':'none';}}
let wasPlaying=false;function frame(){if(audio.playing||wasPlaying){if(wasPlaying&&!audio.playing){position=audio.offset;render();}updatePlayhead();}wasPlaying=audio.playing;requestAnimationFrame(frame);}requestAnimationFrame(frame);
function cancelBuild(message='Generation cancelled. Previous notes kept.'){if(build){clearTimeout(build.timeout);build.worker.terminate();build=null;}status=message;error=false;render();}
function generate(){saveSourceDraft();const source=selectedSource();if(source?.kind!=='generated')return;cancelBuild('Compiling Flow in an isolated worker…');
    const sourceId=source.id,code=source.code,worker=new Worker('./flow-worker.js',{type:'module'});const timeout=setTimeout(()=>cancelBuild('Generation exceeded 10 seconds. Previous notes kept.'),10000);build={worker,timeout,sourceId};status='Compiling Flow… previous notes remain playable.';error=false;render();
    worker.onmessage=({data})=>{if(build?.worker!==worker)return;clearTimeout(timeout);worker.terminate();build=null;const current=doc.sources.find(s=>s.id===sourceId);
        if(!current||current.code!==code){status='Source changed during generation. Result discarded.';render();return;}
        if(data.errors){status=data.errors.map(e=>`${e.line?`Line ${e.line}: `:''}${e.message}`).join('\n');error=true;render();return;}
        const count=data.score.layers.reduce((n,l)=>n+l.notes.length,0);status=`Generated ${count} notes in ${data.score.layers.length} layers. Pitch/velocity preview; project tempo applies.${data.output?'\n'+data.output:''}`;error=false;
        edit('Generate Flow notes',()=>{current.layers=data.score.layers.map(l=>{const old=current.layers.find(x=>x.name===l.name);return old?{...l,id:old.id,instrument:old.instrument,gain:old.gain,pan:old.pan,cutoff:old.cutoff,delay:old.delay}:l;});current.duration=data.score.duration;current.builtCode=code;current.revision++;layerId=current.layers[0]?.id;noteId=null;});};
    worker.onerror=e=>{if(build?.worker!==worker)return;clearTimeout(timeout);worker.terminate();build=null;status=`Flow worker failed: ${e.message}. Check that the local WASM bundle is published.`;error=true;render();};worker.postMessage({source:code});
}
function newClip(generated){edit(generated?'Add Flow clip':'Add note clip',()=>{if(!doc.tracks.length)doc.tracks.push({id:uid(),name:'FLOW',color:COLORS[5],mute:false,solo:false,gain:.7,pan:0});const source={id:uid(),name:generated?'New motif':'New notes',code:generated?SOURCE:'',builtCode:'',revision:1,kind:generated?'generated':'notes',duration:16,layers:[makeLayer('Voice 1',[],0)]};doc.sources.push(source);const c={id:uid(),name:generated?'MOTIF.flow':'NOTES',trackId:selectedTrack()?.id||doc.tracks[0].id,sourceId:source.id,start:Math.floor(position/4)*4,length:16,offset:0};doc.clips.push(c);selected=c.id;layerId=source.layers[0].id;tab='piano';sourceShown=true;});}
async function action(name,el){switch(name){
case'play':if(audio.playing){position=audio.position();audio.stop();render();}else{await audio.play(doc,position);render();}break;
case'stop':audio.stop();position=0;render();break;
case'rewind':position=0;if(audio.playing)await audio.play(doc,0);render();break;
case'loop':edit('Toggle loop',()=>doc.loop.enabled=!doc.loop.enabled);break;
case'undo':case'redo':saveSourceDraft();if(build)cancelBuild();doc=history[name](doc);if(!selectedClip())selected=doc.clips[0]?.id;dirty=true;persist();refreshAudio();render();break;
case'save':saveSourceDraft();download(new Blob([JSON.stringify(doc,null,2)],{type:'application/json'}),`${doc.name}.flowproject`);dirty=false;persist();render();notify('Project saved with source, notes, clip ranges and sound settings.');break;
case'open':$('#project-file').click();break;
case'new':if(dirty&&!confirm('Start a new project? Save a project file first to keep this one.'))break;audio.stop();if(build)cancelBuild();doc={version:1,name:'untitled',bpm:124,loop:{enabled:false,start:0,end:16},tracks:[],sources:[],clips:[]};history=new History();selected=null;position=0;dirty=false;persist();render();break;
case'export':saveSourceDraft();el.disabled=true;notify('Rendering browser preview to stereo WAV…');try{download(await audio.export(clone(doc)),`${doc.name}-preview.wav`);notify('Preview WAV exported.');}finally{el.disabled=false;}break;
case'category':category=el.dataset.category;render();break;
case'library':{const key=el.dataset.key;if(key==='open'||key==='new'){await action(key,el);break;}if(category==='GEN'){newClip(true);if(key==='blank'){edit('Clear Flow source',()=>selectedSource().code='use "@std"\n\n// Write your composition here.\n');}break;}const l=selectedLayer();if(!l){notify('Select or create a clip first.');break;}if(category==='INST')edit('Change preview instrument',()=>l.instrument=key);else{tab='devices';render();}break;}
case'add-flow':newClip(true);break;case'add-notes':newClip(false);break;
case'add-track':edit('Add track',()=>doc.tracks.push({id:uid(),name:`TRACK ${doc.tracks.length+1}`,color:COLORS[doc.tracks.length%6],mute:false,solo:false,gain:.7,pan:0}));break;
case'mute':case'solo':edit(`${name==='mute'?'Mute':'Solo'} track`,()=>{const t=doc.tracks.find(t=>t.id===el.dataset.track);t[name]=!t[name];});break;
case'layout':saveSourceDraft();layout=el.dataset.layout;editorOpen=false;render();break;
case'tab':tab=el.dataset.tab;render();break;
case'toggle-source':saveSourceDraft();sourceShown=!sourceShown;if(layout==='classic'&&sourceShown)editorOpen=true;render();break;
case'expand-source':saveSourceDraft();editorOpen=!editorOpen;render();break;
case'zoom-in':zoom=clamp(zoom+.25,1,4);render();break;case'zoom-out':zoom=clamp(zoom-.25,1,4);render();break;
case'duplicate':if(selectedClip())edit('Duplicate linked clip',()=>selected=duplicateClip(doc,selected));break;
case'split':{const c=selectedClip();if(!c)break;const at=Math.round((audio.playing?audio.position():position)/snap)*snap;if(at<=c.start||at>=c.start+c.length){notify('Click the timeline ruler inside the selected clip, then split.');break;}edit('Split clip',()=>splitClip(doc,selected,at));break;}
case'delete-clip':if(selectedClip())edit('Delete clip',()=>{doc.clips=doc.clips.filter(c=>c.id!==selected);selected=doc.clips[0]?.id;});break;
case'convert':if(selectedClip())edit('Make independent editable notes',()=>{const s=detachClip(doc,selected);layerId=s.layers[0]?.id;noteId=null;});break;
case'transpose-up':case'transpose-down':case'delete-note':{const s=selectedSource(),l=selectedLayer();if(s?.kind==='generated'){notify('Convert this clip to editable notes first.');break;}if(!noteId){notify('Select a note first.');break;}edit(name==='delete-note'?'Delete note':'Transpose note',()=>{if(name==='delete-note')l.notes=l.notes.filter(n=>n.id!==noteId);else{const n=l.notes.find(n=>n.id===noteId);if(n)n.pitch=clamp(n.pitch+(name==='transpose-up'?1:-1),0,127);}});break;}
case'generate':generate();break;case'cancel-build':cancelBuild();break;
case'help':notify('Space: play · S: split · Ctrl+D: duplicate · Delete: delete · Ctrl+Z / Shift+Z: undo/redo · Ctrl+Enter: generate · Ctrl+S: save');break;
}}
$('#app').addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(el)void action(el.dataset.action,el).catch(error=>notify(error.message));});
$('#project-file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>8*1024*1024)throw new Error('Project exceeds the 8 MB prototype limit');const loaded=validateProject(JSON.parse(await file.text()));audio.stop();if(build)cancelBuild();doc=loaded;history=new History();selected=doc.clips.at(-1)?.id;layerId=null;noteId=null;position=0;dirty=false;status='Project opened. Source and note content restored.';error=false;persist();render();}catch(err){notify(err.message);}e.target.value='';});
$('#app').addEventListener('change',e=>{const el=e.target;
    if(el.id==='source-code'){saveSourceDraft();return;}
    if(el.id==='bpm'){const value=clamp(Number(el.value)||124,30,300);edit('Change tempo',()=>doc.bpm=value);}
    if(el.id==='project-name')edit('Rename project',()=>doc.name=el.value.trim().slice(0,120)||'untitled');
    if(el.id==='layer-picker'){layerId=el.value;noteId=null;render();}
    if(el.id==='snap'){snap=Number(el.value);render();}
    if(el.id==='instrument'||el.id==='inspector-instrument')edit('Change preview instrument',()=>selectedLayer().instrument=el.value);
    if(el.dataset.range){const before=rangeBefore||clone(doc),object=rangeObject(el);if(object)object[el.dataset.range]=Number(el.value);history.commit(`Change ${el.dataset.range}`,before,doc);rangeBefore=null;dirty=true;persist();refreshAudio();render();}
});
let rangeBefore=null;
function rangeObject(el){if(el.dataset.target==='track')return doc.tracks.find(t=>t.id===el.dataset.track);if(el.dataset.target==='note'){if(selectedSource()?.kind==='generated')return null;return selectedLayer()?.notes.find(n=>n.id===noteId);}return selectedLayer();}
$('#app').addEventListener('input',e=>{const el=e.target;if(el.id==='search'){search=el.value;const caret=el.selectionStart;render();$('#search').focus();$('#search').setSelectionRange(caret,caret);}
    if(el.id==='source-code'){$('.line-numbers').textContent=Array.from({length:el.value.split('\n').length+1},(_,i)=>i+1).join('\n');$('.source-state').textContent='EDITED';}
    if(el.dataset.range){rangeBefore??=clone(doc);const obj=rangeObject(el);if(obj){obj[el.dataset.range]=Number(el.value);const readout=el.parentElement.querySelector('label span');if(readout)readout.textContent=Number(el.value).toFixed(el.dataset.range==='cutoff'?0:2);}else notify('Convert generated notes before editing their velocity.');}
});
$('#app').addEventListener('scroll',e=>{if(e.target.id==='source-code')$('.line-numbers').scrollTop=e.target.scrollTop;},true);
let drag=null;
$('#app').addEventListener('pointerdown',e=>{
    const splitter=e.target.closest('.splitter,.source-split');if(splitter){e.preventDefault();drag={kind:splitter.classList.contains('splitter')?'vertical':'horizontal',startX:e.clientX,startY:e.clientY,bottom:$('.detail').offsetHeight,source:$('.source-pane').offsetWidth/$('.detail').offsetWidth*100};return;}
    const ruler=e.target.closest('[data-ruler]');if(ruler){const r=ruler.getBoundingClientRect();position=Math.max(0,Math.round((e.clientX-r.left)/r.width*totalBeats()/snap)*snap);if(audio.playing)void audio.play(doc,position);updatePlayhead();return;}
    const key=e.target.closest('[data-key-pitch]');if(key&&selectedLayer())void audio.audition(Number(key.dataset.keyPitch),selectedLayer(),selectedTrack());
    const clipEl=e.target.closest('[data-clip]');if(clipEl){e.preventDefault();const id=clipEl.dataset.clip,isTrim=!!e.target.closest('.clip-handle');selectClip(id);const c=selectedClip(),lane=$(`[data-track-lane="${c.trackId}"]`);drag={kind:isTrim?'trim':'clip',id,before:clone(doc),startX:e.clientX,startY:e.clientY,start:c.start,length:c.length,beatWidth:lane.getBoundingClientRect().width/totalBeats()};return;}
    const noteEl=e.target.closest('[data-note]');if(noteEl){e.preventDefault();noteId=noteEl.dataset.note;layerId=noteEl.dataset.layer;const n=selectedLayer().notes.find(n=>n.id===noteId),field=noteEl.parentElement,rect=field.getBoundingClientRect(),resize=!!e.target.closest('.note-edge');
        if(selectedSource().kind==='notes')drag={kind:resize?'note-length':'note',id:noteId,before:clone(doc),startX:e.clientX,startY:e.clientY,start:n.start,pitch:n.pitch,duration:n.duration,beatWidth:rect.width/selectedClip().length};
        render();if(!audio.playing)void audio.audition(n.pitch,selectedLayer(),selectedTrack());}
});
window.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.startX,dy=e.clientY-drag.startY;
    if(drag.kind==='vertical'){bottomSize=clamp(drag.bottom-dy,230,innerHeight-330);applyPaneSizes();return;}
    if(drag.kind==='horizontal'){sourceSize=clamp(drag.source-dx/$('.detail').offsetWidth*100,25,70);applyPaneSizes();return;}
    const step=Math.round(dx/drag.beatWidth/snap)*snap;
    if(drag.kind==='clip'||drag.kind==='trim'){const c=doc.clips.find(c=>c.id===drag.id);if(drag.kind==='clip'){c.start=clamp(drag.start+step,0,4096-c.length);const lane=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-track-lane]');if(lane)c.trackId=lane.dataset.trackLane;}else c.length=clamp(drag.length+step,snap,Math.max(snap,sourceOf(doc,c).duration-c.offset));}
    else{const n=selectedLayer()?.notes.find(n=>n.id===drag.id);if(n){if(drag.kind==='note-length')n.duration=clamp(drag.duration+step,snap,4096-n.start);else{n.start=clamp(drag.start+step,0,4096-n.duration);n.pitch=clamp(drag.pitch-Math.round(dy/16),0,127);}}}render();
});
function finishDrag(cancel=false){if(!drag)return;const d=drag;drag=null;if(d.before){if(cancel)doc=d.before;else if(history.commit(d.kind==='clip'?'Move clip':d.kind==='trim'?'Trim clip':d.kind==='note'?'Move note':'Resize note',d.before,doc)){dirty=true;persist();refreshAudio();}}render();}
window.addEventListener('pointerup',()=>finishDrag());window.addEventListener('pointercancel',()=>finishDrag(true));window.addEventListener('blur',()=>finishDrag());
$('#app').addEventListener('dblclick',e=>{const field=e.target.closest('.note-field');if(!field||e.target.closest('[data-note]'))return;if(selectedSource()?.kind!=='notes'){notify('Convert to editable notes to draw here.');return;}const rect=field.getBoundingClientRect(),c=selectedClip(),pitch=clamp(Number(field.dataset.hi)-Math.floor((e.clientY-rect.top)/16),0,127),start=Math.floor((e.clientX-rect.left)/rect.width*c.length/snap)*snap+c.offset;edit('Draw note',()=>{const n={id:uid(),start,duration:snap,pitch,velocity:.75};selectedLayer().notes.push(n);noteId=n.id;});});
window.addEventListener('keydown',e=>{const typing=['TEXTAREA','INPUT','SELECT'].includes(e.target.tagName),mod=e.ctrlKey||e.metaKey;
    if(mod&&e.key==='Enter'){e.preventDefault();generate();return;}
    if(mod&&e.key.toLowerCase()==='s'){e.preventDefault();void action('save');return;}
    if(e.key==='Escape'){if(build)cancelBuild();else if(drag)finishDrag(true);else if(editorOpen){editorOpen=false;render();}return;}
    if(typing)return;
    if(e.target.matches('.splitter,.source-split')&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){
        e.preventDefault();if(e.target.matches('.splitter'))bottomSize=clamp($('.detail').offsetHeight+(e.key==='ArrowUp'?20:-20),230,innerHeight-330);
        else sourceSize=clamp($('.source-pane').offsetWidth/$('.detail').offsetWidth*100+(e.key==='ArrowLeft'?2:-2),25,70);applyPaneSizes();return;
    }
    if(e.key==='Enter'&&e.target.dataset.note){noteId=e.target.dataset.note;layerId=e.target.dataset.layer;render();return;}
    let name;if(e.code==='Space')name='play';else if(mod&&e.key.toLowerCase()==='z')name=e.shiftKey?'redo':'undo';else if(mod&&e.key.toLowerCase()==='d')name='duplicate';else if(e.key.toLowerCase()==='s')name='split';else if(e.key==='Delete')name=noteId?'delete-note':'delete-clip';else if(e.key==='Home')name='rewind';else if(e.key==='Enter'&&e.target.dataset.clip){selectClip(e.target.dataset.clip);return;}
    if(name){e.preventDefault();void action(name).catch(err=>notify(err.message));}
});
window.addEventListener('beforeunload',()=>{saveSourceDraft();try{localStorage.setItem('flow-workspace-v1',JSON.stringify(doc));}catch{}audio.stop();build?.worker.terminate();});
render();
