#!/usr/bin/env bash
# scripts/install.sh -- Phase 30 REQ-3: Flow installer.
#
# Defaults to per-user install (~/.local/share/flow/ + ~/.local/bin/flow
# symlink, no sudo). --system installs to /usr/local (sudo required for the
# writes themselves; the script does NOT escalate -- it just fails clearly
# if the user can't write to /usr/local). --install-root overrides for the
# smoke test (tempdir). --local-tarball consumes a publish-output directory
# OR a tar.gz directly so test-install.sh + CI can skip the network fetch.
#
# Idempotent: re-running upgrades in place via ln -sfn + version-stamped
# install dir. Never overwrites a user-customised ~/.config/flow/config.toml.
#
# RESEARCH-locked pattern: prebuilt-tarball model -- no .NET SDK required
# on the user side (see .planning/phases/30-flow-cli-formal-install/30-RESEARCH.md
# offset=520 limit=120).

set -euo pipefail

FLOW_VERSION="${FLOW_VERSION:-0.1.0}"
TARBALL_URL="${FLOW_TARBALL_URL:-https://github.com/noahfreelove/flow-sharp/releases/download/v${FLOW_VERSION}/flow-v${FLOW_VERSION}-linux-x64.tar.gz}"
SYSTEM_INSTALL=0
LOCAL_TARBALL=""
INSTALL_ROOT=""

print_usage() {
  cat <<EOF
Flow installer

Usage:
  install.sh                                   Install to ~/.local/share/flow (per-user, no sudo)
  install.sh --system                          Install to /usr/local/share/flow (system-wide, sudo)
  install.sh --install-root <dir>              Install under <dir>/share/flow and <dir>/bin (for tests)
  install.sh --local-tarball <path>            Use a local publish dir or tar.gz instead of GitHub release

Flags:
  --system            System-wide install (requires sudo for /usr/local writes)
  --install-root DIR  Override install root (test mode)
  --local-tarball P   Local publish dir or tarball; skips network fetch
  -h, --help          Show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --system) SYSTEM_INSTALL=1; shift ;;
    --local-tarball) LOCAL_TARBALL="$2"; shift 2 ;;
    --install-root) INSTALL_ROOT="$2"; shift 2 ;;
    -h|--help) print_usage; exit 0 ;;
    *) echo "Unknown flag: $1" >&2; print_usage >&2; exit 1 ;;
  esac
done

# Determine install paths.
if [[ -n "$INSTALL_ROOT" ]]; then
  SHARE_ROOT="$INSTALL_ROOT/share/flow"
  BIN_ROOT="$INSTALL_ROOT/bin"
elif [[ $SYSTEM_INSTALL -eq 1 ]]; then
  SHARE_ROOT="/usr/local/share/flow"
  BIN_ROOT="/usr/local/bin"
else
  SHARE_ROOT="$HOME/.local/share/flow"
  BIN_ROOT="$HOME/.local/bin"
fi
CONFIG_ROOT="${HOME}/.config/flow"

echo "==> Flow installer v${FLOW_VERSION}"
echo "    SHARE_ROOT=$SHARE_ROOT"
echo "    BIN_ROOT=$BIN_ROOT"
echo "    CONFIG_ROOT=$CONFIG_ROOT"

# Create dirs (mkdir -p is idempotent).
mkdir -p "$SHARE_ROOT" "$BIN_ROOT" "$CONFIG_ROOT"

VERSIONED_DIR="$SHARE_ROOT/flow-v${FLOW_VERSION}"
mkdir -p "$VERSIONED_DIR"

# Acquire payload.
if [[ -n "$LOCAL_TARBALL" ]]; then
  if [[ -d "$LOCAL_TARBALL" ]]; then
    # Directory: copy contents via tar pipe to preserve permissions and
    # avoid trailing-slash subtleties.
    echo "==> Copying from local directory: $LOCAL_TARBALL"
    tar -C "$LOCAL_TARBALL" -cf - . | tar -C "$VERSIONED_DIR" -xf -
  elif [[ -f "$LOCAL_TARBALL" ]]; then
    echo "==> Extracting local tarball: $LOCAL_TARBALL"
    tar -xzf "$LOCAL_TARBALL" -C "$VERSIONED_DIR"
  else
    echo "ERROR: --local-tarball path does not exist: $LOCAL_TARBALL" >&2
    exit 1
  fi
else
  command -v curl >/dev/null || { echo "ERROR: curl required for network install (or pass --local-tarball)" >&2; exit 1; }
  echo "==> Downloading $TARBALL_URL"
  TMP_TAR="$(mktemp -t flow-install.XXXXXX.tar.gz)"
  curl -fsSL "$TARBALL_URL" -o "$TMP_TAR"
  tar -xzf "$TMP_TAR" -C "$VERSIONED_DIR"
  rm -f "$TMP_TAR"
fi

# Verify payload.
if [[ ! -x "$VERSIONED_DIR/flow" ]]; then
  echo "ERROR: $VERSIONED_DIR/flow not present or not executable after extract." >&2
  exit 1
fi

# Idempotent symlink: ln -sfn replaces any existing symlink in place
# (the -f forces overwrite; -n ensures it doesn't recurse into an existing
# symlinked directory).
ln -sfn "$VERSIONED_DIR/flow" "$BIN_ROOT/flow"

# Default config -- only if absent (never overwrite user customisation).
# Guard pattern: `[[ ! -f "$CONFIG_ROOT/config.toml" ]]` -- the literal
# filename in the test predicate also satisfies the grep-based acceptance
# check in 30-05-PLAN.md task 1.
if [[ ! -f "$CONFIG_ROOT/config.toml" ]]; then
  CONFIG_FILE="$CONFIG_ROOT/config.toml"
  cat > "$CONFIG_FILE" <<EOF
# Flow default config -- auto-generated by install.sh
# See https://github.com/noahfreelove/flow-sharp for documentation.

install_path = "$VERSIONED_DIR"

# Uncomment to override built-in defaults:
# default_audio_device = "alsa_output.usb-..."
# default_tempo = 120
# default_timesig = "4/4"
# stdlib_search_path = ["/usr/share/my-flow-modules"]
EOF
  echo "==> Wrote default config: $CONFIG_FILE"
fi

# PATH check (POSIX-safe: colon-fenced needle in colon-fenced haystack
# avoids prefix/suffix false matches).
case ":$PATH:" in
  *":$BIN_ROOT:"*) ;;
  *)
    echo ""
    echo "WARNING: $BIN_ROOT is not on your PATH."
    if [[ $SYSTEM_INSTALL -eq 0 && -z "$INSTALL_ROOT" ]]; then
      echo "Add this line to your ~/.bashrc or ~/.zshrc:"
      echo "  export PATH=\"\$HOME/.local/bin:\$PATH\""
    fi
    ;;
esac

echo ""
echo "==> Installed flow v${FLOW_VERSION} -> $VERSIONED_DIR"
echo "==> Symlinked $BIN_ROOT/flow -> $VERSIONED_DIR/flow"
echo "==> Run: flow version"
