using System.Net;
using System.Text;

namespace FlowCli.Doc;

// Phase 41 Plan 41-03 DOC-01 — DocModel[] → docs/reference/index.html (D-09).
//
// A clean single-column developer reference, NOT the skeuomorphic flowlang.dev
// marketing site (CONTEXT D-62 discretion: "functional, readable; no design
// contract"). Hand-rolled string templating with deterministic "\n" newlines so
// the output is diffable (no DocFX / docusaurus — D-09). Light + dark via
// `prefers-color-scheme`; NO JavaScript dependency. Monospace styled <pre> for
// signatures + examples. Entries grouped by the CLAUDE.md "Built-in Function
// Categories" (DocCollector.ClassifyCategory). `[example failed]` annotations
// render inline for any DocModel with ExampleFailures.
//
// Bump ContentHashCache.GeneratorVersion whenever this template changes so the
// cache forces a full regen (Pitfall 6).
public sealed class HtmlEmitter
{
    public const string FileName = "index.html";

    public string Emit(IReadOnlyList<DocModel> models)
    {
        var sb = new StringBuilder();
        sb.Append("<!DOCTYPE html>\n");
        sb.Append("<html lang=\"en\">\n<head>\n");
        sb.Append("<meta charset=\"utf-8\">\n");
        sb.Append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
        sb.Append("<title>Flow Language Reference</title>\n");
        sb.Append("<style>\n").Append(Css).Append("</style>\n");
        sb.Append("</head>\n<body>\n");

        sb.Append("<header><h1>Flow Language Reference</h1>");
        sb.Append("<p class=\"sub\">Generated by <code>flow doc</code> from <code>///</code> doc-comments + built-in metadata.</p></header>\n");

        var groups = models
            .GroupBy(m => m.Category)
            .OrderBy(g => g.Key, StringComparer.Ordinal)
            .ToList();

        // Top index (no JS — plain anchor links).
        sb.Append("<nav class=\"toc\"><h2>Categories</h2><ul>\n");
        foreach (var g in groups)
        {
            var anchor = Anchor(g.Key);
            sb.Append("<li><a href=\"#").Append(anchor).Append("\">")
              .Append(Esc(g.Key)).Append("</a> <span class=\"count\">(")
              .Append(g.Count()).Append(")</span></li>\n");
        }
        sb.Append("</ul></nav>\n");

        sb.Append("<main>\n");
        foreach (var g in groups)
        {
            var anchor = Anchor(g.Key);
            sb.Append("<section class=\"category\">\n");
            sb.Append("<h2 id=\"").Append(anchor).Append("\">").Append(Esc(g.Key)).Append("</h2>\n");
            foreach (var m in g)
                EmitEntry(sb, m);
            sb.Append("</section>\n");
        }
        sb.Append("</main>\n");

        sb.Append("<footer><p>Flow — an interpreted, statically-typed language for music production.</p></footer>\n");
        sb.Append("</body>\n</html>\n");
        return sb.ToString();
    }

    /// <summary>Emit + write index.html into <paramref name="outDir"/>; returns the file path.</summary>
    public string Write(string outDir, IReadOnlyList<DocModel> models)
    {
        Directory.CreateDirectory(outDir);
        var path = Path.Combine(outDir, FileName);
        File.WriteAllText(path, Emit(models));
        return path;
    }

    private static void EmitEntry(StringBuilder sb, DocModel m)
    {
        sb.Append("<article class=\"entry\" id=\"fn-").Append(Anchor(m.Name)).Append("\">\n");
        sb.Append("<h3>").Append(Esc(m.Name));
        if (m.Source == DocSource.Builtin)
            sb.Append(" <span class=\"badge\">builtin</span>");
        sb.Append("</h3>\n");
        sb.Append("<pre class=\"sig\">").Append(Esc(m.Signature)).Append("</pre>\n");

        if (!string.IsNullOrWhiteSpace(m.Summary))
            sb.Append("<p class=\"summary\">").Append(Esc(m.Summary)).Append("</p>\n");

        if (m.Params.Count > 0)
        {
            sb.Append("<table class=\"params\"><tbody>\n");
            foreach (var p in m.Params)
            {
                sb.Append("<tr><td class=\"pname\"><code>").Append(Esc(p.Name)).Append("</code></td>");
                sb.Append("<td class=\"pdesc\">").Append(Esc(p.Description)).Append("</td></tr>\n");
            }
            sb.Append("</tbody></table>\n");
        }

        for (int i = 0; i < m.Examples.Count; i++)
        {
            sb.Append("<div class=\"example\">\n");
            sb.Append("<pre class=\"code\">").Append(Esc(m.Examples[i])).Append("</pre>\n");
            // ExampleFailures is a same-length list: index i corresponds to
            // Examples[i]. Empty string = pass (no annotation); non-empty =
            // the [example failed] text for that specific example.
            if (i < m.ExampleFailures.Count && !string.IsNullOrEmpty(m.ExampleFailures[i]))
                sb.Append("<p class=\"failed\">").Append(Esc(m.ExampleFailures[i])).Append("</p>\n");
            sb.Append("</div>\n");
        }

        sb.Append("</article>\n");
    }

    private static string Esc(string s) => WebUtility.HtmlEncode(s);

    private static string Anchor(string s)
    {
        var sb = new StringBuilder(s.Length);
        foreach (var ch in s.ToLowerInvariant())
        {
            if (char.IsLetterOrDigit(ch)) sb.Append(ch);
            else if (ch is ' ' or '-' or '_' or '/' or '&') sb.Append('-');
        }
        return sb.ToString().Trim('-');
    }

    // Light + dark via prefers-color-scheme; no JS. CSS custom properties keep
    // the two themes in one stylesheet.
    private const string Css = """
:root {
  --bg: #ffffff; --fg: #1a1a1a; --muted: #666; --accent: #2a6db5;
  --card: #f6f7f9; --border: #e0e3e8; --code-bg: #f0f2f5; --code-fg: #11314f;
  --badge-bg: #e7f0fa; --badge-fg: #2a6db5; --fail-bg: #fdeaea; --fail-fg: #b22020;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #14171c; --fg: #e6e8ec; --muted: #9aa3ad; --accent: #6db1ff;
    --card: #1c2128; --border: #2a313a; --code-bg: #11151b; --code-fg: #9fd0ff;
    --badge-bg: #1d2c3d; --badge-fg: #6db1ff; --fail-bg: #3a1f1f; --fail-fg: #ff8a8a;
  }
}
* { box-sizing: border-box; }
body {
  margin: 0; padding: 0 1.25rem 4rem;
  font-family: system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
  line-height: 1.55; color: var(--fg); background: var(--bg);
  max-width: 56rem; margin-left: auto; margin-right: auto;
}
header { padding: 2rem 0 1rem; border-bottom: 1px solid var(--border); }
header h1 { margin: 0 0 .25rem; font-size: 1.9rem; }
.sub { color: var(--muted); margin: 0; }
.toc { margin: 1.5rem 0; padding: 1rem 1.25rem; background: var(--card); border: 1px solid var(--border); border-radius: 8px; }
.toc h2 { margin: 0 0 .5rem; font-size: 1.1rem; }
.toc ul { list-style: none; margin: 0; padding: 0; columns: 2; }
.toc li { margin: .15rem 0; break-inside: avoid; }
.toc a { color: var(--accent); text-decoration: none; }
.toc a:hover { text-decoration: underline; }
.count { color: var(--muted); font-size: .85em; }
.category { margin: 2.5rem 0; }
.category > h2 { font-size: 1.4rem; padding-bottom: .3rem; border-bottom: 2px solid var(--border); }
.entry { margin: 1.5rem 0; padding: 1rem 1.25rem; background: var(--card); border: 1px solid var(--border); border-radius: 8px; }
.entry h3 { margin: 0 0 .5rem; font-size: 1.15rem; font-family: ui-monospace, "SF Mono", Menlo, Consolas, monospace; }
.badge { font-size: .7rem; font-weight: 600; vertical-align: middle; padding: .1rem .45rem; border-radius: 999px; background: var(--badge-bg); color: var(--badge-fg); font-family: system-ui, sans-serif; }
pre { font-family: ui-monospace, "SF Mono", Menlo, Consolas, monospace; font-size: .9rem; overflow-x: auto; }
.sig { margin: 0 0 .6rem; padding: .55rem .75rem; background: var(--code-bg); color: var(--code-fg); border-radius: 6px; font-weight: 600; }
.summary { margin: .4rem 0 .75rem; }
.params { border-collapse: collapse; width: 100%; margin: .5rem 0; font-size: .92rem; }
.params td { padding: .25rem .5rem; vertical-align: top; border-bottom: 1px solid var(--border); }
.pname { white-space: nowrap; }
.params code { background: var(--code-bg); color: var(--code-fg); padding: .05rem .35rem; border-radius: 4px; }
.example { margin: .6rem 0; }
.code { margin: 0; padding: .55rem .75rem; background: var(--code-bg); color: var(--code-fg); border-radius: 6px; border-left: 3px solid var(--accent); }
.failed { margin: .35rem 0 0; padding: .4rem .65rem; background: var(--fail-bg); color: var(--fail-fg); border-radius: 6px; font-size: .85rem; font-family: ui-monospace, monospace; }
footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid var(--border); color: var(--muted); font-size: .9rem; }
""";
}
