using System.Text;

namespace FlowCli.Doc;

// Phase 41 Plan 41-03 DOC-01 — DocModel[] → docs/reference/reference.md (D-09).
//
// A single greppable/diffable Markdown sibling to index.html so the reference is
// reviewable in-repo (search `### transpose` in your editor, diff doc edits in a
// PR). Same category grouping as the HTML, same `[example failed]` annotation.
// Deterministic "\n" newlines for stable diffs.
//
// Bump ContentHashCache.GeneratorVersion whenever this template changes (Pitfall 6).
public sealed class MarkdownEmitter
{
    public const string FileName = "reference.md";

    public string Emit(IReadOnlyList<DocModel> models)
    {
        var sb = new StringBuilder();
        sb.Append("# Flow Language Reference\n\n");
        sb.Append("Generated by `flow doc` from `///` doc-comments + built-in metadata.\n\n");

        var groups = models
            .GroupBy(m => m.Category)
            .OrderBy(g => g.Key, StringComparer.Ordinal)
            .ToList();

        // Table of contents.
        sb.Append("## Categories\n\n");
        foreach (var g in groups)
            sb.Append("- [").Append(g.Key).Append("](#")
              .Append(Anchor(g.Key)).Append(") (").Append(g.Count()).Append(")\n");
        sb.Append('\n');

        foreach (var g in groups)
        {
            sb.Append("## ").Append(g.Key).Append("\n\n");
            foreach (var m in g)
                EmitEntry(sb, m);
        }
        return sb.ToString();
    }

    /// <summary>Emit + write reference.md into <paramref name="outDir"/>; returns the file path.</summary>
    public string Write(string outDir, IReadOnlyList<DocModel> models)
    {
        Directory.CreateDirectory(outDir);
        var path = Path.Combine(outDir, FileName);
        File.WriteAllText(path, Emit(models));
        return path;
    }

    private static void EmitEntry(StringBuilder sb, DocModel m)
    {
        // WR-03: m.Name / m.Signature / example bodies are harvested from arbitrary
        // user `.flow` files via DocCollector. Escape Markdown specials in the heading
        // and ``` sequences in fenced bodies so a proc/param containing `#`, `[`, a
        // backtick, or a literal ``` cannot break rendering or inject formatting (the
        // HtmlEmitter already HtmlEncodes consistently; this is its Markdown twin).
        sb.Append("### ").Append(EscHeading(m.Name));
        if (m.Source == DocSource.Builtin)
            sb.Append(" _(builtin)_");
        sb.Append("\n\n");

        sb.Append("```flow\n").Append(EscFenced(m.Signature)).Append("\n```\n\n");

        if (!string.IsNullOrWhiteSpace(m.Summary))
            sb.Append(m.Summary).Append("\n\n");

        if (m.Params.Count > 0)
        {
            sb.Append("| Parameter | Description |\n|---|---|\n");
            foreach (var p in m.Params)
                sb.Append("| `").Append(EscCell(p.Name)).Append("` | ")
                  .Append(EscCell(p.Description)).Append(" |\n");
            sb.Append('\n');
        }

        for (int i = 0; i < m.Examples.Count; i++)
        {
            sb.Append("```flow\n").Append(EscFenced(m.Examples[i])).Append("\n```\n");
            // ExampleFailures is a same-length list: index i corresponds to
            // Examples[i]. Empty string = pass (no annotation); non-empty =
            // the [example failed] text for that specific example.
            if (i < m.ExampleFailures.Count && !string.IsNullOrEmpty(m.ExampleFailures[i]))
                sb.Append("> ").Append(m.ExampleFailures[i]).Append("\n");
            sb.Append('\n');
        }
    }

    private static string EscCell(string s) =>
        s.Replace("|", "\\|").Replace("\n", " ");

    // WR-03: a literal ``` inside a signature or example body would terminate the
    // fenced code block early and leak the rest as raw Markdown. Backslash-escape it.
    private static string EscFenced(string s) =>
        s.Replace("```", "\\`\\`\\`");

    // WR-03: minimal inline-Markdown escape for an ATX heading. Escapes the
    // characters that can alter heading rendering or inject emphasis/links/code.
    private static string EscHeading(string s)
    {
        var sb = new StringBuilder(s.Length);
        foreach (var ch in s)
        {
            if (ch is '\\' or '`' or '#' or '[' or ']' or '*' or '_')
                sb.Append('\\');
            sb.Append(ch);
        }
        return sb.ToString();
    }

    private static string Anchor(string s)
    {
        var sb = new StringBuilder(s.Length);
        foreach (var ch in s.ToLowerInvariant())
        {
            if (char.IsLetterOrDigit(ch)) sb.Append(ch);
            else if (ch is ' ' or '-' or '_' or '/' or '&') sb.Append('-');
        }
        // GitHub-style anchors collapse runs but keep it simple + deterministic.
        return sb.ToString().Trim('-');
    }
}
